### ISSUE TITLE
Perhaps mention that everyone can get access by watching twitch streams

### ISSUE THREAD

**Issue by Lyceris-chan** [CactusPuppy/isow2outyet#2]
https://news.blizzard.com/en-us/overwatch/23798985/welcome-to-the-first-overwatch-2-pvp-beta

**Comment by Lyceris-chan** [comment]
![image](https://user-images.githubusercontent.com/52329982/165363264-5babdd19-57aa-4eea-9614-516d9a89db11.png)

seems like the site broke

**Comment by CactusPuppy** [comment]
I'm so sorry I missed this feedback. I was mostly focused on updating https://ow2countdown.com and totally forgot to update this site.
